-- --------------------------------------------------------
-- 호스트:                          127.0.0.1
-- 서버 버전:                        10.4.6-MariaDB - mariadb.org binary distribution
-- 서버 OS:                        Win64
-- HeidiSQL 버전:                  9.5.0.5196
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- investing.com 데이터베이스 구조 내보내기
CREATE DATABASE IF NOT EXISTS `investing.com` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `investing.com`;

-- 테이블 investing.com.economic_events 구조 내보내기
CREATE TABLE IF NOT EXISTS `economic_events` (
  `cd` int(4) unsigned NOT NULL,
  `nm_us` varchar(100) DEFAULT NULL,
  `nm_kr` varchar(100) DEFAULT NULL,
  `link` varchar(200) DEFAULT NULL,
  `ctry` varchar(200) DEFAULT NULL,
  `period` char(1) DEFAULT NULL,
  `imp_us` int(1) DEFAULT NULL,
  `imp_kr` int(1) DEFAULT NULL,
  PRIMARY KEY (`cd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 테이블 데이터 investing.com.economic_events:~24 rows (대략적) 내보내기
/*!40000 ALTER TABLE `economic_events` DISABLE KEYS */;
INSERT INTO `economic_events` (`cd`, `nm_us`, `nm_kr`, `link`, `ctry`, `period`, `imp_us`, `imp_kr`) VALUES
	(1, 'U.S. ADP Nonfarm Employment Change ', 'ADP 비농업부문 고용 변화', 'https://www.investing.com/economic-calendar/adp-nonfarm-employment-change-1', 'US', 'M', 3, 3),
	(8, 'Average Hourly Earnings (MoM)', NULL, 'https://www.investing.com/economic-calendar/average-hourly-earnings-8', 'US', NULL, 2, NULL),
	(25, 'U.S. Building Permits ', '건축승인건수', 'https://www.investing.com/economic-calendar/building-permits-25', 'US', 'M', 3, 3),
	(29, 'Business Inventories (MoM)', NULL, 'https://www.investing.com/economic-calendar/business-inventories-29', 'US', NULL, 2, NULL),
	(31, 'Capacity Utilization Rate', NULL, 'https://www.investing.com/economic-calendar/capacity-utilization-rate-31', 'US', NULL, 1, NULL),
	(38, 'Chicago PMI', NULL, 'https://www.investing.com/economic-calendar/chicago-pmi-38', 'US', NULL, 2, NULL),
	(45, 'Construction Spending (MoM)', NULL, 'https://www.investing.com/economic-calendar/construction-spending-45', 'US', NULL, 1, NULL),
	(48, 'U.S. CB Consumer Confidence ', 'CB 소비자신뢰지수', 'https://www.investing.com/economic-calendar/cb-consumer-confidence-48', 'US', 'M', 3, 3),
	(52, 'Consumer Credit', NULL, 'https://www.investing.com/economic-calendar/consumer-credit-52', 'US', NULL, 1, NULL),
	(56, 'U.S. Core Consumer Price Index (CPI) MoM', '근원 소비자물가지수', 'https://www.investing.com/economic-calendar/core-cpi-56', 'US', 'M', 3, 3),
	(59, 'U.S. Core Durable Goods Orders MoM', '근원 내구재수주', 'https://www.investing.com/economic-calendar/core-durable-goods-orders-59', 'US', 'M', 3, 3),
	(61, 'Core PCE Price Index (MoM)', NULL, 'https://www.investing.com/economic-calendar/core-pce-price-index-61', 'US', NULL, 2, NULL),
	(62, 'Core PPI (MoM)', NULL, 'https://www.investing.com/economic-calendar/core-ppi-62', 'US', NULL, 2, NULL),
	(63, 'U.S. Core Retail Sales MoM	', '근원 소매판매', 'https://www.investing.com/economic-calendar/core-retail-sales-63', 'US', 'M', 3, 3),
	(69, 'CPI (MoM)', NULL, 'https://www.investing.com/economic-calendar/cpi-69', 'US', NULL, 2, NULL),
	(75, 'U.S. Crude Oil Inventories ', '원유재고', 'https://www.investing.com/economic-calendar/eia-crude-oil-inventories-75', 'US', 'W', 3, 3),
	(81, 'Current Account', NULL, 'https://www.investing.com/economic-calendar/current-account-81', 'US', NULL, 2, NULL),
	(85, 'Total Vehicle Sales', NULL, 'https://www.investing.com/economic-calendar/total-vehicle-sales-85', 'US', NULL, 1, NULL),
	(86, 'Durable Goods Orders (MoM)', NULL, 'https://www.investing.com/economic-calendar/durable-goods-orders-86', 'US', NULL, 2, NULL),
	(99, 'U.S. Existing Home Sales ', '기존주택판매', 'https://www.investing.com/economic-calendar/existing-home-sales-99', 'US', 'M', 3, 3),
	(100, 'Factory Orders (MoM)', NULL, 'https://www.investing.com/economic-calendar/factory-orders-100', 'US', NULL, 2, NULL),
	(151, 'Housing Starts', NULL, 'https://www.investing.com/economic-calendar/housing-starts-151', 'US', NULL, 2, NULL),
	(153, 'Import Price Index (MoM)', NULL, 'https://www.investing.com/economic-calendar/import-price-index-153', 'US', NULL, 2, NULL),
	(161, 'Industrial Production (MoM)', NULL, 'https://www.investing.com/economic-calendar/industrial-production-161', 'US', NULL, 2, NULL),
	(168, 'Fed Interest Rate Decision ', '금리결정 ', 'https://www.investing.com/economic-calendar/interest-rate-decision-168', 'US', NULL, 3, 3),
	(173, 'U.S. ISM Manufacturing Purchasing Managers Index (PMI) ', 'ISM 제조업구매자지수', 'https://www.investing.com/economic-calendar/ism-manufacturing-pmi-173', 'US', 'M', 3, 3),
	(174, 'ISM Manufacturing Prices', NULL, 'https://www.investing.com/economic-calendar/ism-manufacturing-prices-174', 'US', NULL, 1, NULL),
	(176, 'U.S. ISM Non-Manufacturing Purchasing Managers Index (PMI) ', 'ISM 비제조업구매자지수', 'https://www.investing.com/economic-calendar/ism-non-manufacturing-pmi-176', 'US', 'M', 3, 3),
	(218, 'NAHB Housing Market Index', NULL, 'https://www.investing.com/economic-calendar/nahb-housing-market-index-218', 'US', NULL, 1, NULL),
	(222, 'U.S. New Home Sales ', '신규 주택판매', 'https://www.investing.com/economic-calendar/new-home-sales-222', 'US', 'M', 3, 3),
	(227, 'U.S. Nonfarm Payrolls ', '비농업고용지수', 'https://www.investing.com/economic-calendar/nonfarm-payrolls-227', 'US', 'M', 3, 3),
	(228, 'Nonfarm Productivity (QoQ)  ', NULL, 'https://www.investing.com/economic-calendar/nonfarm-productivity-228', 'US', NULL, 2, NULL),
	(232, 'U.S. Pending Home Sales MoM ', '잠정주택매매', 'https://www.investing.com/economic-calendar/pending-home-sales-232', 'US', 'M', 3, 3),
	(234, 'Personal Income (MoM)', NULL, 'https://www.investing.com/economic-calendar/personal-income-234', 'US', NULL, 1, NULL),
	(235, 'Personal Spending (MoM)', NULL, 'https://www.investing.com/economic-calendar/personal-spending-235', 'US', NULL, 2, NULL),
	(236, 'U.S. Philadelphia Fed Manufacturing Index ', '필라델피아 연준 제조업활동지수', 'https://www.investing.com/economic-calendar/philadelphia-fed-manufacturing-index-236', 'US', 'M', 3, 3),
	(238, 'U.S. Producer Price Index (PPI) MoM ', '생산자물가지수', 'https://www.investing.com/economic-calendar/ppi-238', 'US', 'M', 3, 3),
	(256, 'U.S. Retail Sales MoM ', '소매판매', 'https://www.investing.com/economic-calendar/retail-sales-256', 'US', 'M', 3, 3),
	(263, 'Richmond Manufacturing Index', NULL, 'https://www.investing.com/economic-calendar/richmond-manufacturing-index-263', 'US', NULL, 1, NULL),
	(283, 'TIC Net Long-Term Transactions', NULL, 'https://www.investing.com/economic-calendar/tic-net-long-term-transactions-283', 'US', NULL, 2, NULL),
	(286, 'Trade Balance', NULL, 'https://www.investing.com/economic-calendar/trade-balance-286', 'US', NULL, 2, NULL),
	(294, 'Initial Jobless Claims', NULL, 'https://www.investing.com/economic-calendar/initial-jobless-claims-294', 'US', NULL, 2, NULL),
	(300, 'U.S. Unemployment Rate ', '실업률', 'https://www.investing.com/economic-calendar/unemployment-rate-300', 'US', 'M', 3, 3),
	(303, 'Unit Labor Costs (QoQ)  ', NULL, 'https://www.investing.com/economic-calendar/unit-labor-costs-303', 'US', NULL, 2, NULL),
	(305, 'Wholesale Inventories (MoM)', NULL, 'https://www.investing.com/economic-calendar/wholesale-inventories-305', 'US', NULL, 1, NULL),
	(320, 'Michigan Consumer Sentiment  ', NULL, 'https://www.investing.com/economic-calendar/michigan-consumer-sentiment-320', 'US', NULL, 2, NULL),
	(323, 'NY Empire State Manufacturing Index', NULL, 'https://www.investing.com/economic-calendar/ny-empire-state-manufacturing-index-323', 'US', NULL, 2, NULL),
	(325, 'IBD/TIPP Economic Optimism', NULL, 'https://www.investing.com/economic-calendar/ibd-tipp-economic-optimism-325', 'US', NULL, 1, NULL),
	(327, 'House Price Index (MoM)', NULL, 'https://www.investing.com/economic-calendar/house-price-index-327', 'US', NULL, 1, NULL),
	(329, 'S&P/CS HPI Composite - 20 n.s.a. (YoY)', NULL, 'https://www.investing.com/economic-calendar/s-p-cs-hpi-composite-20-n.s.a.-329', 'US', NULL, 2, NULL),
	(331, 'Employment Cost Index (QoQ)', NULL, 'https://www.investing.com/economic-calendar/employment-cost-index-331', 'US', NULL, 2, NULL),
	(333, 'Challenger Job Cuts (YoY)', NULL, 'https://www.investing.com/economic-calendar/challenger-job-cuts-333', 'US', NULL, 1, NULL),
	(343, 'GDP Price Index (QoQ)  ', NULL, 'https://www.investing.com/economic-calendar/gdp-price-index-343', 'US', NULL, 2, NULL),
	(369, 'Federal Budget Balance', NULL, 'https://www.investing.com/economic-calendar/federal-budget-balance-369', 'US', NULL, 2, NULL),
	(375, 'U.S. Gross Domestic Product (GDP) QoQ', 'GDP', 'https://www.investing.com/economic-calendar/gdp-375', 'US', 'Q', 3, 3),
	(379, 'Average Weekly Hours', NULL, 'https://www.investing.com/economic-calendar/average-weekly-hours-379', 'US', NULL, 1, NULL),
	(380, 'MBA Mortgage Applications (WoW)', NULL, 'https://www.investing.com/economic-calendar/mba-mortgage-applications-380', 'US', NULL, 1, NULL),
	(381, 'Bloomberg Consumer Confidence', NULL, 'https://www.investing.com/economic-calendar/bloomberg-consumer-comfort-index-381', 'US', NULL, 1, NULL),
	(386, 'Natural Gas Storage', NULL, 'https://www.investing.com/economic-calendar/natural-gas-storage-386', 'US', NULL, 1, NULL),
	(389, 'Michigan Inflation Expectations  ', NULL, 'https://www.investing.com/economic-calendar/michigan-inflation-expectations-389', 'US', NULL, 1, NULL),
	(459, 'CPI (YoY)', NULL, 'https://www.investing.com/economic-calendar/chinese-cpi-459', 'CN', NULL, 2, NULL),
	(460, 'Fixed Asset Investment (YoY)', NULL, 'https://www.investing.com/economic-calendar/chinese-fixed-asset-investment-460', 'CN', NULL, 2, NULL),
	(461, 'China Gross Domestic Product (GDP) YoY', '중국 GDP', 'https://www.investing.com/economic-calendar/chinese-gdp-461', 'CN', 'Q', 3, 3),
	(462, 'China Industrial Production YoY ', '중국 산업생산', 'https://www.investing.com/economic-calendar/chinese-industrial-production-462', 'CN', 'M', 3, 3),
	(464, 'PPI (YoY)', NULL, 'https://www.investing.com/economic-calendar/chinese-ppi-464', 'CN', NULL, 2, NULL),
	(466, 'Trade Balance (USD)', NULL, 'https://www.investing.com/economic-calendar/chinese-trade-balance-466', 'CN', NULL, 2, NULL),
	(467, 'CPI (YoY)', NULL, 'https://www.investing.com/economic-calendar/south-korean-cpi-467', 'KR', NULL, 2, NULL),
	(484, 'MBA Delinquency Rates (QoQ)', NULL, 'https://www.investing.com/economic-calendar/mba-delinquency-rates-484', 'US', NULL, 1, NULL),
	(485, 'Gasoline Inventories', NULL, 'https://www.investing.com/economic-calendar/gasoline-inventories-485', 'US', NULL, 1, NULL),
	(522, 'Continuing Jobless Claims', NULL, 'https://www.investing.com/economic-calendar/continuing-jobless-claims-522', 'US', NULL, 1, NULL),
	(523, 'Chicago Fed National Activity', NULL, 'https://www.investing.com/economic-calendar/chicago-fed-national-activity-523', 'US', NULL, 1, NULL),
	(528, 'Private Nonfarm Payrolls', NULL, 'https://www.investing.com/economic-calendar/private-nonfarm-payrolls-528', 'US', NULL, 2, NULL),
	(537, 'NFIB Small Business Optimism', NULL, 'https://www.investing.com/economic-calendar/nfib-small-business-optimism-537', 'US', NULL, 1, NULL),
	(567, '4-Week Bill Auction', NULL, 'https://www.investing.com/economic-calendar/4-week-bill-auction-567', 'US', NULL, 1, NULL),
	(568, '3-Month Bill Auction', NULL, 'https://www.investing.com/economic-calendar/3-month-bill-auction-568', 'US', NULL, 1, NULL),
	(569, '2-Year Note Auction', NULL, 'https://www.investing.com/economic-calendar/2-year-note-auction-569', 'US', NULL, 1, NULL),
	(570, '5-Year Note Auction', NULL, 'https://www.investing.com/economic-calendar/5-year-note-auction-570', 'US', NULL, 1, NULL),
	(571, '10-Year Note Auction', NULL, 'https://www.investing.com/economic-calendar/10-year-note-auction-571', 'US', NULL, 2, NULL),
	(572, '30-Year Bond Auction', NULL, 'https://www.investing.com/economic-calendar/30-year-bond-auction-572', 'US', NULL, 1, NULL),
	(594, 'China Manufacturing Purchasing Managers Index (PMI) ', '중국 제조업 구매관리자지수', 'https://www.investing.com/economic-calendar/chinese-manufacturing-pmi-594', 'CN', 'M', 3, 3),
	(595, 'Exports (YoY)', NULL, 'https://www.investing.com/economic-calendar/chinese-exports-595', 'CN', NULL, 2, NULL),
	(596, 'Caixin Services PMI', NULL, 'https://www.investing.com/economic-calendar/chinese-caixin-services-pmi-596', 'CN', NULL, 2, NULL),
	(654, 'US Foreign Buying, T-bonds', NULL, 'https://www.investing.com/economic-calendar/foreign-buying,-t-bonds-654', 'US', NULL, 1, NULL),
	(655, 'Redbook (MoM)', NULL, 'https://www.investing.com/economic-calendar/redbook-655', 'US', NULL, 1, NULL),
	(656, 'API Weekly Crude Oil Stock', NULL, 'https://www.investing.com/economic-calendar/api-weekly-crude-stock-656', 'US', NULL, 2, NULL),
	(658, 'Dallas Fed Mfg Business Index', NULL, 'https://www.investing.com/economic-calendar/dallas-fed-mfg-business-index-658', 'US', NULL, 1, NULL),
	(660, 'CB Employment Trends Index', NULL, 'https://www.investing.com/economic-calendar/cb-employment-trends-index-660', 'US', NULL, 1, NULL),
	(661, 'ISM-New York Index', NULL, 'https://www.investing.com/economic-calendar/new-york-napm-661', 'US', NULL, 1, NULL),
	(662, 'KC Fed Composite Index', NULL, 'https://www.investing.com/economic-calendar/kc-fed-composite-index-662', 'US', NULL, 1, NULL),
	(663, 'Overall Net Capital Flow', NULL, 'https://www.investing.com/economic-calendar/overall-net-capital-flow-663', 'US', NULL, 1, NULL),
	(679, '6-Month Bill Auction', NULL, 'https://www.investing.com/economic-calendar/6-month-bill-auction-679', 'US', NULL, 1, NULL),
	(680, '52-Week Bill Auction', NULL, 'https://www.investing.com/economic-calendar/52-week-bill-auction-680', 'US', NULL, 1, NULL),
	(681, '3-Year Note Auction', NULL, 'https://www.investing.com/economic-calendar/3-year-note-auction-681', 'US', NULL, 1, NULL),
	(682, '7-Year Note Auction', NULL, 'https://www.investing.com/economic-calendar/7-year-note-auction-682', 'US', NULL, 1, NULL),
	(733, 'CPI (YoY)', NULL, 'https://www.investing.com/economic-calendar/cpi-733', 'US', NULL, 1, NULL),
	(734, 'PPI (YoY)', NULL, 'https://www.investing.com/economic-calendar/ppi-734', 'US', NULL, 1, NULL),
	(735, 'Core PPI (YoY)', NULL, 'https://www.investing.com/economic-calendar/core-ppi-735', 'US', NULL, 1, NULL),
	(736, 'Core CPI (YoY)', NULL, 'https://www.investing.com/economic-calendar/core-cpi-736', 'US', NULL, 2, NULL),
	(743, 'CPI (MoM)', NULL, 'https://www.investing.com/economic-calendar/chinese-cpi-743', 'CN', NULL, 2, NULL),
	(753, 'China Caixin Manufacturing Purchasing Managers Index (PMI) ', 'Caixin 중국 제조업 구매관리자지수', 'https://www.investing.com/economic-calendar/chinese-caixin-manufacturing-pmi-753', 'CN', 'M', 3, 3),
	(829, 'Manufacturing PMI', NULL, 'https://www.investing.com/economic-calendar/manufacturing-pmi-829', 'US', NULL, 2, NULL),
	(831, 'Non-Manufacturing PMI', NULL, 'https://www.investing.com/economic-calendar/chinese-non-manufacturing-pmi-831', 'CN', NULL, 2, NULL),
	(867, 'Imports (YoY)', NULL, 'https://www.investing.com/economic-calendar/chinese-imports-867', 'CN', NULL, 2, NULL),
	(868, 'GDP (QoQ)', NULL, 'https://www.investing.com/economic-calendar/chinese-gdp-868', 'CN', NULL, 2, NULL),
	(885, 'Building Permits (MoM)', NULL, 'https://www.investing.com/economic-calendar/building-permits-885', 'US', NULL, 2, NULL),
	(886, 'All Car Sales', NULL, 'https://www.investing.com/economic-calendar/all-car-sales-886', 'US', NULL, 1, NULL),
	(887, 'Cleveland CPI (MoM)', NULL, 'https://www.investing.com/economic-calendar/cleveland-cpi-887', 'US', NULL, 1, NULL),
	(888, 'Challenger Job Cuts', NULL, 'https://www.investing.com/economic-calendar/challenger-job-cuts-888', 'US', NULL, 1, NULL),
	(889, 'Domestic Car Sales', NULL, 'https://www.investing.com/economic-calendar/domestic-car-sales-889', 'US', NULL, 1, NULL),
	(890, 'Real Earnings (MoM)', NULL, 'https://www.investing.com/economic-calendar/real-earnings-890', 'US', NULL, 1, NULL),
	(891, 'Existing Home Sales (MoM)', NULL, 'https://www.investing.com/economic-calendar/existing-home-sales-891', 'US', NULL, 2, NULL),
	(892, 'Export Price Index (MoM)', NULL, 'https://www.investing.com/economic-calendar/export-price-index-892', 'US', NULL, 2, NULL),
	(893, 'Factory orders ex transportation (MoM)', NULL, 'https://www.investing.com/economic-calendar/factory-orders-ex-transportation-893', 'US', NULL, 1, NULL),
	(895, 'Real Personal Consumption (MoM)', NULL, 'https://www.investing.com/economic-calendar/real-personal-consumption-895', 'US', NULL, 1, NULL),
	(896, 'New Home Sales (MoM)', NULL, 'https://www.investing.com/economic-calendar/new-home-sales-896', 'US', NULL, 2, NULL),
	(897, 'House Price Index (YoY)', NULL, 'https://www.investing.com/economic-calendar/house-price-index-897', 'US', NULL, 1, NULL),
	(898, 'Housing Starts (MoM)', NULL, 'https://www.investing.com/economic-calendar/housing-starts-898', 'US', NULL, 2, NULL),
	(899, 'KC Fed Manufacturing Index', NULL, 'https://www.investing.com/economic-calendar/kc-fed-manufacturing-index-899', 'US', NULL, 1, NULL),
	(900, 'Michigan Consumer Expectations  ', NULL, 'https://www.investing.com/economic-calendar/michigan-consumer-expectations-900', 'US', NULL, 2, NULL),
	(901, 'Michigan Current Conditions  ', NULL, 'https://www.investing.com/economic-calendar/michigan-current-conditions-901', 'US', NULL, 1, NULL),
	(902, 'Pending Home Sales Index', NULL, 'https://www.investing.com/economic-calendar/pending-home-sales-index-902', 'US', NULL, 1, NULL),
	(903, 'TIC Net Long-Term Transactions including Swaps', NULL, 'https://www.investing.com/economic-calendar/tic-net-long-term-transactions-including-swaps-903', 'US', NULL, 1, NULL),
	(905, 'Core PCE Price Index (YoY)', NULL, 'https://www.investing.com/economic-calendar/core-pce-price-index-905', 'US', NULL, 2, NULL),
	(907, 'Philly Fed Business Conditions', NULL, 'https://www.investing.com/economic-calendar/philly-fed-business-conditions-907', 'US', NULL, 1, NULL),
	(908, 'Philly Fed Employment', NULL, 'https://www.investing.com/economic-calendar/philly-fed-employment-908', 'US', NULL, 2, NULL),
	(911, 'Redbook (YoY)', NULL, 'https://www.investing.com/economic-calendar/redbook-911', 'US', NULL, 1, NULL),
	(913, 'S&P/CS HPI Composite - 20 n.s.a. (MoM)', NULL, 'https://www.investing.com/economic-calendar/s-p-cs-hpi-composite-20-n.s.a.-913', 'US', NULL, 1, NULL),
	(914, 'Real Consumer Spending  ', NULL, 'https://www.investing.com/economic-calendar/real-consumer-spending-914', 'US', NULL, 1, NULL),
	(917, 'EIA Weekly Distillates Stocks', NULL, 'https://www.investing.com/economic-calendar/eia-weekly-distillates-stocks-917', 'US', NULL, 1, NULL),
	(1037, '5-Year TIPS Auction', NULL, 'https://www.investing.com/economic-calendar/5-year-tip-auction-1037', 'US', NULL, 1, NULL),
	(1038, '10-Year TIPS Auction', NULL, 'https://www.investing.com/economic-calendar/10-year-tips-auction-1038', 'US', NULL, 1, NULL),
	(1040, '30-Year TIPS Auction', NULL, 'https://www.investing.com/economic-calendar/30-year-tips-auction-1040', 'US', NULL, 1, NULL),
	(1041, 'Jobless Claims 4-Week Avg.', NULL, 'https://www.investing.com/economic-calendar/jobless-claims-4-week-avg.-1041', 'US', NULL, 1, NULL),
	(1042, 'MBA 30-Year Mortgage Rate', NULL, 'https://www.investing.com/economic-calendar/mba-30-year-mortgage-rate-1042', 'US', NULL, 1, NULL),
	(1046, 'ISM Manufacturing Employment', NULL, 'https://www.investing.com/economic-calendar/ism-manufacturing-employment-1046', 'US', NULL, 2, NULL),
	(1047, 'Goods Orders Non Defense Ex Air (MoM)', NULL, 'https://www.investing.com/economic-calendar/goods-orders-non-defense-ex-air-1047', 'US', NULL, 1, NULL),
	(1048, 'ISM Non-Manufacturing Employment', NULL, 'https://www.investing.com/economic-calendar/ism-non-manufacturing-employment-1048', 'US', NULL, 2, NULL),
	(1049, 'ISM Non-Manufacturing Prices', NULL, 'https://www.investing.com/economic-calendar/ism-non-manufacturing-prices-1049', 'US', NULL, 1, NULL),
	(1050, 'ISM Non-Manufacturing New Orders', NULL, 'https://www.investing.com/economic-calendar/ism-non-manufacturing-new-orders-1050', 'US', NULL, 1, NULL),
	(1057, 'U.S. JOLTs Job Openings ', '노동부 채용 및 노동 회전률 조사', 'https://www.investing.com/economic-calendar/jolts-job-openings-1057', 'US', 'M', 3, 3),
	(1060, 'New Loans', NULL, 'https://www.investing.com/economic-calendar/chinese-new-loans-1060', 'CN', NULL, 2, NULL),
	(1062, 'Services PMI', NULL, 'https://www.investing.com/economic-calendar/services-pmi-1062', 'US', NULL, 2, NULL),
	(1084, 'PBoC Reserve Requirement Ratio', NULL, 'https://www.investing.com/economic-calendar/pboc-reserve-requirement-ratio-1084', 'CN', NULL, 2, NULL),
	(1162, 'Investing.com Gold Index', NULL, 'https://www.investing.com/economic-calendar/investing.com-gold-index-1162', 'US', NULL, 2, NULL),
	(1163, 'Investing.com S&P 500 Index', NULL, 'https://www.investing.com/economic-calendar/investing.com-s-p-500-index-1163', 'US', NULL, 2, NULL),
	(1226, 'Core CPI Index', NULL, 'https://www.investing.com/economic-calendar/core-cpi-index-1226', 'US', NULL, 1, NULL),
	(1287, 'House Price Index', NULL, 'https://www.investing.com/economic-calendar/monthly-home-price-index-1287', 'US', NULL, 1, NULL),
	(1307, 'Manufacturing Production (MoM)', NULL, 'https://www.investing.com/economic-calendar/manufacturing-output-1307', 'US', NULL, 1, NULL),
	(1315, 'Corporate Profits (QoQ)  ', NULL, 'https://www.investing.com/economic-calendar/corporate-profits-1315', 'US', NULL, 1, NULL),
	(1334, 'S&P/CS HPI Composite - 20 s.a. (MoM)', NULL, 'https://www.investing.com/economic-calendar/s-p-cs-hpi-composite---20-s.a.-1334', 'US', NULL, 1, NULL),
	(1427, 'Mortgage Market Index', NULL, 'https://www.investing.com/economic-calendar/mortgage-market-index-1427', 'US', NULL, 1, NULL),
	(1428, 'Mortgage Refinance Index', NULL, 'https://www.investing.com/economic-calendar/mortgage-refinance-index-1428', 'US', NULL, 1, NULL),
	(1437, 'All Truck Sales', NULL, 'https://www.investing.com/economic-calendar/all-truck-sales-1437', 'US', NULL, 1, NULL),
	(1444, 'Dallas Fed Services Revenues', NULL, 'https://www.investing.com/economic-calendar/dallas-fed-services-revenues-1444', 'US', NULL, 1, NULL),
	(1445, 'Domestic Truck Sales', NULL, 'https://www.investing.com/economic-calendar/domestic-truck-sales-1445', 'US', NULL, 1, NULL),
	(1446, 'Durables Excluding Defense (MoM)', NULL, 'https://www.investing.com/economic-calendar/durables-excluding-defense-1446', 'US', NULL, 1, NULL),
	(1468, 'GDP Sales', NULL, 'https://www.investing.com/economic-calendar/gdp-sales-1468', 'US', NULL, 1, NULL),
	(1483, 'ISM Manufacturing New Orders Index', NULL, 'https://www.investing.com/economic-calendar/ism-manufacturing-new-orders-index-1483', 'US', NULL, 1, NULL),
	(1484, 'ISM Non-Manufacturing Business Activity', NULL, 'https://www.investing.com/economic-calendar/ism-non-manufacturing-business-activity-1484', 'US', NULL, 1, NULL),
	(1492, 'Markit Composite PMI', NULL, 'https://www.investing.com/economic-calendar/markit-composite-pmi-1492', 'US', NULL, 2, NULL),
	(1494, 'MBA Purchase Index', NULL, 'https://www.investing.com/economic-calendar/mba-purchase-index-1494', 'US', NULL, 1, NULL),
	(1501, 'Philly Fed CAPEX Index', NULL, 'https://www.investing.com/economic-calendar/philly-fed-capex-index-1501', 'US', NULL, 1, NULL),
	(1502, 'Philly Fed New Orders', NULL, 'https://www.investing.com/economic-calendar/philly-fed-new-orders-1502', 'US', NULL, 1, NULL),
	(1503, 'Philly Fed Prices Paid', NULL, 'https://www.investing.com/economic-calendar/philly-fed-prices-paid-1503', 'US', NULL, 1, NULL),
	(1506, 'Retail Control (MoM)', NULL, 'https://www.investing.com/economic-calendar/retail-control-1506', 'US', NULL, 1, NULL),
	(1507, 'Retail Sales Ex Gas/Autos (MoM)', NULL, 'https://www.investing.com/economic-calendar/retail-sales-ex-gas-autos-1507', 'US', NULL, 1, NULL),
	(1510, 'Richmond Manufacturing Shipments', NULL, 'https://www.investing.com/economic-calendar/richmond-manufacturing-shipments-1510', 'US', NULL, 1, NULL),
	(1511, 'Richmond Services Index', NULL, 'https://www.investing.com/economic-calendar/richmond-services-index-1511', 'US', NULL, 1, NULL),
	(1519, 'Texas Services Sector Outlook', NULL, 'https://www.investing.com/economic-calendar/texas-services-sector-outlook-1519', 'US', NULL, 1, NULL),
	(1524, 'Employment Benefits (QoQ)', NULL, 'https://www.investing.com/economic-calendar/employment-benefits-1524', 'US', NULL, 1, NULL),
	(1526, 'Employment Wages (QoQ)', NULL, 'https://www.investing.com/economic-calendar/employment-wages-1526', 'US', NULL, 1, NULL),
	(1531, 'Manufacturing Payrolls', NULL, 'https://www.investing.com/economic-calendar/manufacturing-payrolls-1531', 'US', NULL, 1, NULL),
	(1533, 'Payrolls Benchmark', NULL, 'https://www.investing.com/economic-calendar/payrolls-benchmark-1533', 'US', NULL, 1, NULL),
	(1534, 'Payrolls Benchmark, n.s.a.', NULL, 'https://www.investing.com/economic-calendar/payrolls-benchmark,-n.s.a.-1534', 'US', NULL, 1, NULL),
	(1548, 'Core PCE Prices  ', NULL, 'https://www.investing.com/economic-calendar/core-pce-prices-1548', 'US', NULL, 1, NULL),
	(1549, 'CPI Index, n.s.a.', NULL, 'https://www.investing.com/economic-calendar/cpi-index,-n.s.a.-1549', 'US', NULL, 1, NULL),
	(1550, 'Dallas Fed PCE', NULL, 'https://www.investing.com/economic-calendar/dallas-fed-pce-1550', 'US', NULL, 1, NULL),
	(1568, 'Michigan 5-Year Inflation Expectations  ', NULL, 'https://www.investing.com/economic-calendar/michigan-5-year-inflation-expectations-1568', 'US', NULL, 1, NULL),
	(1571, 'PCE Prices', NULL, 'https://www.investing.com/economic-calendar/pce-prices-1571', 'US', NULL, 1, NULL),
	(1579, 'Government Payrolls', NULL, 'https://www.investing.com/economic-calendar/government-payrolls-1579', 'US', NULL, 1, NULL),
	(1581, 'Participation Rate', NULL, 'https://www.investing.com/economic-calendar/participation-rate-1581', 'US', NULL, 2, NULL),
	(1618, 'CFTC Gold speculative net positions', NULL, 'https://www.investing.com/economic-calendar/cftc-gold-speculative-positions-1618', 'US', NULL, 2, NULL),
	(1619, 'CFTC S&P 500 speculative net positions', NULL, 'https://www.investing.com/economic-calendar/cftc-s-p-500-speculative-positions-1619', 'US', NULL, 2, NULL),
	(1620, 'CFTC Copper speculative net positions', NULL, 'https://www.investing.com/economic-calendar/cftc-copper-speculative-positions-1620', 'US', NULL, 1, NULL),
	(1621, 'CFTC Silver speculative net positions', NULL, 'https://www.investing.com/economic-calendar/cftc-silver-speculative-positions-1621', 'US', NULL, 1, NULL),
	(1650, 'Goods Trade Balance', NULL, 'https://www.investing.com/economic-calendar/goods-trade-balance-1650', 'US', NULL, 2, NULL),
	(1652, 'U.S. Baker Hughes Oil Rig Count', NULL, 'https://www.investing.com/economic-calendar/baker-hughes-u.s.-rig-count-1652', 'US', NULL, 2, NULL),
	(1653, 'CFTC Crude Oil speculative net positions', NULL, 'https://www.investing.com/economic-calendar/cftc-crude-oil-speculative-positions-1653', 'US', NULL, 2, NULL),
	(1657, 'Cushing Crude Oil Inventories', NULL, 'https://www.investing.com/economic-calendar/eia-weekly-cushing-oil-inventories-1657', 'US', NULL, 2, NULL),
	(1658, 'Crude Oil Imports', NULL, 'https://www.investing.com/economic-calendar/eia-weekly-crude-imports-1658', 'US', NULL, 1, NULL),
	(1659, 'Heating Oil Stockpiles', NULL, 'https://www.investing.com/economic-calendar/eia-weekly-heatoil-stock-1659', 'US', NULL, 1, NULL),
	(1660, 'Distillate Fuel Production', NULL, 'https://www.investing.com/economic-calendar/eia-weekly-distillate-fuel-production-1660', 'US', NULL, 1, NULL),
	(1661, 'Gasoline Production', NULL, 'https://www.investing.com/economic-calendar/eia-weekly-gasoline-production-1661', 'US', NULL, 1, NULL),
	(1670, 'U6 Unemployment Rate', NULL, 'https://www.investing.com/economic-calendar/u6-unemployment-rate-1670', 'US', NULL, 1, NULL),
	(1746, 'Import Price Index ex Petroleum (MoM)', NULL, 'https://www.investing.com/economic-calendar/import-price-index-ex-petroleum-1746', 'US', NULL, 1, NULL),
	(1747, 'Import Price Index (YoY)', NULL, 'https://www.investing.com/economic-calendar/import-price-index-1747', 'US', NULL, 1, NULL),
	(1748, 'Export Price Index (YoY)', NULL, 'https://www.investing.com/economic-calendar/export-price-index-1748', 'US', NULL, 1, NULL),
	(1751, 'Cap Goods Ship Non Defense Ex Air (MoM)', NULL, 'https://www.investing.com/economic-calendar/cap-goods-ship-non-defense-ex-air-1751', 'US', NULL, 2, NULL),
	(1755, 'Industrial Production (YoY)', NULL, 'https://www.investing.com/economic-calendar/industrial-production-1755', 'US', NULL, 2, NULL),
	(1762, 'Exports', NULL, 'https://www.investing.com/economic-calendar/exports-1762', 'US', NULL, 2, NULL),
	(1763, 'Imports', NULL, 'https://www.investing.com/economic-calendar/imports-1763', 'US', NULL, 2, NULL),
	(1765, 'Wholesale Trade Sales (MoM)', NULL, 'https://www.investing.com/economic-calendar/wholesale-trade-sales-1765', 'US', NULL, 1, NULL),
	(1771, 'PCE Deflator (MoM)', NULL, 'https://www.investing.com/economic-calendar/pce-deflator-1771', 'US', NULL, 2, NULL),
	(1772, 'PCE Deflator (YoY)', NULL, 'https://www.investing.com/economic-calendar/pce-deflator-1772', 'US', NULL, 2, NULL),
	(1777, 'Average Hourly Earnings (YoY) (YoY)', NULL, 'https://www.investing.com/economic-calendar/average-hourly-earnings-1777', 'US', NULL, 2, NULL),
	(1793, 'Chinese Unemployment Rate', NULL, 'https://www.investing.com/economic-calendar/chinese-unemployment-rate-1793', 'CN', NULL, 2, NULL),
	(1801, '8-Week Bill Auction', NULL, 'https://www.investing.com/economic-calendar/8-week-bill-auction-1801', 'US', NULL, 1, NULL),
	(1810, 'U.S. Baker Hughes Total Rig Count', NULL, 'https://www.investing.com/economic-calendar/u.s.-baker-hughes-total-rig-count-1810', 'US', NULL, 2, NULL),
	(1811, 'CFTC Soybeans speculative net positions', NULL, 'https://www.investing.com/economic-calendar/cftc-soybeans-speculative-positions-1811', 'US', NULL, 1, NULL),
	(1812, 'CFTC Wheat speculative net positions', NULL, 'https://www.investing.com/economic-calendar/cftc-wheat-speculative-positions-1812', 'US', NULL, 1, NULL),
	(1813, 'CFTC Corn speculative net positions', NULL, 'https://www.investing.com/economic-calendar/cftc-corn-speculative-positions-1813', 'US', NULL, 1, NULL),
	(1820, 'CFTC Natural Gas speculative net positions', NULL, 'https://www.investing.com/economic-calendar/cftc-natural-gas-speculative-positions-1820', 'US', NULL, 1, NULL),
	(1821, 'CFTC Aluminium speculative net positions', NULL, 'https://www.investing.com/economic-calendar/cftc-aluminium-speculative-net-positions-1821', 'US', NULL, 1, NULL),
	(1878, 'Retail Sales (YoY)', NULL, 'https://www.investing.com/economic-calendar/retail-sales-1878', 'US', NULL, 1, NULL),
	(1887, 'Retail Inventories Ex Auto', NULL, 'https://www.investing.com/economic-calendar/retail-inventories-ex-auto-1887', 'US', NULL, 2, NULL),
	(1913, 'Chinese Composite PMI', NULL, 'https://www.investing.com/economic-calendar/chinese-composite-pmi-1913', 'CN', NULL, 2, NULL);
/*!40000 ALTER TABLE `economic_events` ENABLE KEYS */;

-- 테이블 investing.com.index_master 구조 내보내기
CREATE TABLE IF NOT EXISTS `index_master` (
  `cd` varchar(8) NOT NULL,
  `nm_us` varchar(64) NOT NULL,
  `nm_kr` varchar(128) DEFAULT NULL,
  `curr_id` int(8) NOT NULL,
  `smlID` int(16) NOT NULL,
  `type` char(1) DEFAULT NULL,
  PRIMARY KEY (`cd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 테이블 데이터 investing.com.index_master:~9 rows (대략적) 내보내기
/*!40000 ALTER TABLE `index_master` DISABLE KEYS */;
INSERT INTO `index_master` (`cd`, `nm_us`, `nm_kr`, `curr_id`, `smlID`, `type`) VALUES
	('CL', 'Crude Oil WTI Futures', NULL, 8849, 300060, 'F'),
	('DJI', 'Dow Jones Industrial Average', NULL, 169, 2030170, 'I'),
	('GC', 'Gold Futures', NULL, 8830, 300004, 'F'),
	('HG', 'Copper Futures', NULL, 8831, 300012, 'F'),
	('NDX', 'Nasdaq 100', NULL, 20, 2030165, 'I'),
	('NG', 'Natural Gas Futures', NULL, 8862, 300092, 'F'),
	('SI', 'Silver Futures', NULL, 8836, 300044, 'F'),
	('SPX', 'S&P 500', NULL, 166, 2030167, 'I'),
	('STOXX50E', 'Euro Stoxx 50', NULL, 175, 2030175, 'I');
/*!40000 ALTER TABLE `index_master` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
